[project]
name = "fastapi-kafka"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "confluent-kafka>=2.10.0",
    "fastapi>=0.115.12",
    "uvicorn>=0.34.2",
]
